apiVersion: v2
name: blackfire
description: An unofficial Helm chart for Blackfire.io
home: https://blackfire.io/
sources:
  - https://blackfire.io
version: 1.7.1
appVersion: 2
icon: https://raw.githubusercontent.com/kubmeta/helm-charts/master/charts/blackfire/chart-icon.jpg
sources:
- https://github.com/kubmeta/helm-charts/tree/master/charts/blackfire
maintainers:
- name: Kubmeta Maintainers
  email: devops@kubmeta.com
keywords:
  - blackfire
  - php
  - profiler